apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: ratel-postgres
  namespace: ratel-backend

spec:
  serviceName: "ratel-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: ratel-postgres

  template:
    metadata:
      labels:
        app: ratel-postgres

    spec:
      containers:
        - name: ratel-postgres
          image: postgres:16
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password

            - name: RATEL_BACKEND_USERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: ratel-backend-users-password

          volumeMounts:
            - name: ratel-postgres
              mountPath: /var/lib/postgresql/data

            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d

          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            periodSeconds: 5
            failureThreshold: 60

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

      volumes:
        - name: postgres-init-scripts
          configMap:
            name: postgres-init-scripts

  volumeClaimTemplates:
    - metadata:
        name: ratel-postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
