apiVersion: v1
kind: Secret

metadata:
  name: postgres-secrets
  namespace: ratel-backend

type: Opaque

stringData:
  postgres-password: "dQB4DblsWvPsMCf6bA2eD3KnMT2Lpq8r"
  ratel-backend-users-password: "ddTAR38WtYsAwZE1vZNJw3fHp754fasf"
