apiVersion: v1
kind: Secret

metadata:
  name: backend-creatures-secrets
  namespace: ratel-backend

type: Opaque

stringData:
  ConnectionStrings__MainConnection: "Server=ratel-postgres;Port=5432;Database=ratel_backend_creatures;User Id=ratel_backend_creatures;Password=ddTAR38WtYsAwZE1vZNJw3fHp754fasf;"
  AdministratorAccountSettings__Login: "shakti"
  AdministratorAccountSettings__Password: "2ThcmsSDm0XgrQmadt6eszRmOkb7hK"
