apiVersion: v1
kind: Secret

metadata:
  name: backend-secrets
  namespace: ratel-backend

type: Opaque

stringData:
  ConnectionStrings__MainConnection: "Server=ratel-postgres;Port=5432;Database=ratel_backend_users;User Id=ratel_backend_users;Password=ddTAR38WtYsAwZE1vZNJw3fHp754fasf;"
