FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /source

# Copy projects and restore as distinct layers
COPY ratel_backend_users/*.csproj ratel_backend_users/
COPY ratel_backend_users_dtos/*.csproj ratel_backend_users_dtos/

RUN dotnet restore ratel_backend_users/ratel_backend_users.csproj

# Copy everything else and build app
COPY . .
WORKDIR /source/ratel_backend_users
RUN dotnet publish -c Release -o /app --no-restore

# Final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app ./

ENTRYPOINT ["dotnet", "ratel_backend_users.dll", "--urls=http://+:9000"]
