FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /source

# Copy projects
COPY ratel_backend_users_dtos/*.csproj ratel_backend_users_dtos/
COPY ratel_backend_users_client/*.csproj ratel_backend_users_client/
COPY ratel_backend_users_e2e/*.csproj ratel_backend_users_e2e/

# Restore as distinct layer
RUN dotnet restore ratel_backend_users_e2e/ratel_backend_users_e2e.csproj

# Copy sources
COPY . .

# Run rests
ENTRYPOINT ["dotnet", "test", \
    "ratel_backend_users_e2e/ratel_backend_users_e2e.csproj", \
    "--configuration", "Release", \
    "--no-restore", \
    "--logger", "console;verbosity=detailed"]
