apiVersion: v1
kind: ConfigMap

metadata:
  name: fluent-bit-config
  namespace: ratel-monitoring

data:
  fluent-bit.conf: |
    [SERVICE]
        Flush               1
        Daemon              Off
        Log_Level           info
        Parsers_File        parsers.conf

    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        Tag                 kube.*
        Parser              cri
        Mem_Buf_Limit       50MB
        Skip_Long_Lines     On
        Refresh_Interval    5

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        Kube_Tag_Prefix     kube.var.log.containers.

    [OUTPUT]
        Name                loki
        Match               *

        Host                loki
        Port                3100

        Labels              job=fluent-bit
        Auto_Kubernetes_Labels on

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>.+?) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
