apiVersion: apps/v1
kind: Deployment

metadata:
  name: tempo
  namespace: ratel-monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tempo

  template:
    metadata:
      labels:
        app: tempo

    spec:
      containers:
        - name: tempo

          image: grafana/tempo:latest

          args:
            - "-config.file=/etc/tempo/tempo.yaml"

          ports:
            - containerPort: 3200
            - containerPort: 4317
            - containerPort: 4318

          volumeMounts:
            - name: config
              mountPath: /etc/tempo

            - name: storage
              mountPath: /var/tempo

      volumes:
        - name: config
          configMap:
            name: tempo-config

        - name: storage
          persistentVolumeClaim:
            claimName: tempo-data
