apiVersion: v1
kind: ConfigMap

metadata:
  name: grafana-datasources
  namespace: ratel-monitoring

data:
  loki.yaml: |
    apiVersion: 1

    datasources:
      - name: Loki
        uid: loki-datasource-uid
        isDefault: true
        editable: false
        type: loki
        access: proxy
        url: http://loki:3100

        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: '"TraceId":"(\w+)"'
              datasourceUid: tempo-datasource-uid
              url: '$${__value.raw}'

  tempo.yaml: |
    apiVersion: 1

    datasources:
      - name: Tempo
        uid: tempo-datasource-uid
        isDefault: false
        editable: false
        type: tempo
        access: proxy
        url: http://tempo:3200

        jsonData:
          tracesToLogsV2:
            datasourceUid: loki-datasource-uid

            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"

            filterByTraceID: true
            filterBySpanID: false

          serviceMap:
            datasourceUid: prometheus-datasource-uid

          nodeGraph:
            enabled: true

  prometheus.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus-datasource-uid
        isDefault: false
        editable: false
        type: prometheus
        access: proxy
        url: http://prometheus:9090
