apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy

metadata:
  name: ratel-envoy-proxy
  namespace: ratel-backend

spec:
  ipFamily: DualStack

  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          metallb.io/loadBalancerIPs: "172.18.255.200,fc00:f853:ccd:e793:ffff:ffff:ffff:ff00"
