FROM mcr.microsoft.com/dotnet/sdk:10.0 AS restore

WORKDIR /source

COPY Directory.Build.props .
COPY Directory.Packages.props .
COPY Ratel.Backend.slnx .

COPY ratel_backend_users/ratel_backend_users_dtos/*.csproj \
     ratel_backend_users/ratel_backend_users_dtos/

COPY ratel_backend_users/ratel_backend_users_client/*.csproj \
     ratel_backend_users/ratel_backend_users_client/

COPY ratel_backend_users/ratel_backend_users_e2e/*.csproj \
     ratel_backend_users/ratel_backend_users_e2e/

COPY ratel_shared/ratel_shared_auxiliary/*.csproj \
     ratel_shared/ratel_shared_auxiliary/

COPY ratel_shared/ratel_shared_e2e/*.csproj \
     ratel_shared/ratel_shared_e2e/

RUN --mount=type=cache,id=ratel-nuget,target=/root/.nuget/packages,sharing=locked \
    dotnet restore \
        ratel_backend_users/ratel_backend_users_e2e/ratel_backend_users_e2e.csproj \
    && cp -a /root/.nuget/packages /nuget-packages

# Copying cache
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS tests

WORKDIR /source

COPY --from=restore /source/ /source/
COPY --from=restore /nuget-packages/ /root/.nuget/packages/

# Copy sources
COPY . .

# Build tests
RUN dotnet build \
    ratel_backend_users/ratel_backend_users_e2e/ratel_backend_users_e2e.csproj \
    --configuration Release \
    --no-restore

# Run compiled tests
ENTRYPOINT ["dotnet", "test", \
    "ratel_backend_users/ratel_backend_users_e2e/ratel_backend_users_e2e.csproj", \
    "--configuration", "Release", \
    "--no-build", \
    "--no-restore", \
    "--logger", "console;verbosity=detailed"]
